# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(534, 181)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.temp = QtWidgets.QLabel(self.centralwidget)
        self.temp.setGeometry(QtCore.QRect(2, 2, 41, 16))
        font = QtGui.QFont()
        font.setFamily("等线")
        self.temp.setFont(font)
        self.temp.setObjectName("temp")
        self.pwm = QtWidgets.QLabel(self.centralwidget)
        self.pwm.setGeometry(QtCore.QRect(152, 2, 51, 16))
        font = QtGui.QFont()
        font.setFamily("等线")
        self.pwm.setFont(font)
        self.pwm.setObjectName("pwm")
        self.borderL = QtWidgets.QLabel(self.centralwidget)
        self.borderL.setGeometry(QtCore.QRect(302, 2, 41, 16))
        font = QtGui.QFont()
        font.setFamily("等线")
        self.borderL.setFont(font)
        self.borderL.setObjectName("borderL")
        self.borderH = QtWidgets.QLabel(self.centralwidget)
        self.borderH.setGeometry(QtCore.QRect(422, 2, 41, 16))
        font = QtGui.QFont()
        font.setFamily("等线")
        self.borderH.setFont(font)
        self.borderH.setObjectName("borderH")
        self.ip = QtWidgets.QLabel(self.centralwidget)
        self.ip.setGeometry(QtCore.QRect(2, 135, 21, 16))
        font = QtGui.QFont()
        font.setFamily("等线")
        self.ip.setFont(font)
        self.ip.setObjectName("ip")
        self.ipDot1 = QtWidgets.QLabel(self.centralwidget)
        self.ipDot1.setGeometry(QtCore.QRect(53, 135, 16, 16))
        font = QtGui.QFont()
        font.setFamily("等线")
        self.ipDot1.setFont(font)
        self.ipDot1.setObjectName("ipDot1")
        self.ipDot2 = QtWidgets.QLabel(self.centralwidget)
        self.ipDot2.setGeometry(QtCore.QRect(93, 135, 16, 16))
        font = QtGui.QFont()
        font.setFamily("等线")
        self.ipDot2.setFont(font)
        self.ipDot2.setObjectName("ipDot2")
        self.ipDot3 = QtWidgets.QLabel(self.centralwidget)
        self.ipDot3.setGeometry(QtCore.QRect(133, 135, 16, 16))
        font = QtGui.QFont()
        font.setFamily("等线")
        self.ipDot3.setFont(font)
        self.ipDot3.setObjectName("ipDot3")
        self.version = QtWidgets.QLabel(self.centralwidget)
        self.version.setGeometry(QtCore.QRect(240, 135, 100, 16))
        font = QtGui.QFont()
        font.setFamily("等线")
        self.version.setFont(font)
        self.version.setObjectName("version")
        self.mac = QtWidgets.QLabel(self.centralwidget)
        self.mac.setGeometry(QtCore.QRect(350, 135, 180, 16))
        font = QtGui.QFont()
        font.setFamily("等线")
        self.mac.setFont(font)
        self.mac.setObjectName("mac")
        self.tempLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.tempLCD.setGeometry(QtCore.QRect(2, 20, 140, 60))
        font = QtGui.QFont()
        font.setFamily("等线")
        self.tempLCD.setFont(font)
        self.tempLCD.setSmallDecimalPoint(True)
        self.tempLCD.setDigitCount(4)
        self.tempLCD.setProperty("value", 0.0)
        self.tempLCD.setObjectName("tempLCD")
        self.pwmLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.pwmLCD.setGeometry(QtCore.QRect(152, 20, 140, 60))
        font = QtGui.QFont()
        font.setFamily("等线")
        self.pwmLCD.setFont(font)
        self.pwmLCD.setSmallDecimalPoint(True)
        self.pwmLCD.setDigitCount(4)
        self.pwmLCD.setProperty("value", 0.0)
        self.pwmLCD.setObjectName("pwmLCD")
        self.borderLLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.borderLLCD.setGeometry(QtCore.QRect(302, 20, 110, 60))
        font = QtGui.QFont()
        font.setFamily("等线")
        self.borderLLCD.setFont(font)
        self.borderLLCD.setSmallDecimalPoint(True)
        self.borderLLCD.setDigitCount(3)
        self.borderLLCD.setProperty("value", 0.0)
        self.borderLLCD.setObjectName("borderLLCD")
        self.borderHLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.borderHLCD.setGeometry(QtCore.QRect(422, 20, 110, 60))
        font = QtGui.QFont()
        font.setFamily("等线")
        self.borderHLCD.setFont(font)
        self.borderHLCD.setSmallDecimalPoint(True)
        self.borderHLCD.setDigitCount(3)
        self.borderHLCD.setProperty("value", 0.0)
        self.borderHLCD.setObjectName("borderHLCD")
        self.ipSeg1 = QtWidgets.QLineEdit(self.centralwidget)
        self.ipSeg1.setGeometry(QtCore.QRect(20, 133, 31, 21))
        font = QtGui.QFont()
        font.setFamily("等线")
        self.ipSeg1.setFont(font)
        self.ipSeg1.setObjectName("ipSeg1")
        self.ipSeg2 = QtWidgets.QLineEdit(self.centralwidget)
        self.ipSeg2.setGeometry(QtCore.QRect(60, 133, 31, 21))
        font = QtGui.QFont()
        font.setFamily("等线")
        self.ipSeg2.setFont(font)
        self.ipSeg2.setObjectName("ipSeg2")
        self.ipSeg3 = QtWidgets.QLineEdit(self.centralwidget)
        self.ipSeg3.setGeometry(QtCore.QRect(100, 133, 31, 21))
        font = QtGui.QFont()
        font.setFamily("等线")
        self.ipSeg3.setFont(font)
        self.ipSeg3.setObjectName("ipSeg3")
        self.ipSeg4 = QtWidgets.QLineEdit(self.centralwidget)
        self.ipSeg4.setGeometry(QtCore.QRect(140, 133, 31, 21))
        font = QtGui.QFont()
        font.setFamily("等线")
        self.ipSeg4.setFont(font)
        self.ipSeg4.setObjectName("ipSeg4")
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setGeometry(QtCore.QRect(175, 132, 50, 23))
        font = QtGui.QFont()
        font.setFamily("等线")
        self.connectButton.setFont(font)
        self.connectButton.setObjectName("connectButton")
        self.tempBar = QtWidgets.QProgressBar(self.centralwidget)
        self.tempBar.setGeometry(QtCore.QRect(2, 84, 530, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(8)
        self.tempBar.setFont(font)
        self.tempBar.setStyleSheet("QProgressBar::chunk {background-color: #06B025;}")
        self.tempBar.setProperty("value", 0)
        self.tempBar.setAlignment(QtCore.Qt.AlignCenter)
        self.tempBar.setFormat("TEMP")
        self.tempBar.setObjectName("tempBar")
        self.pwmBar = QtWidgets.QProgressBar(self.centralwidget)
        self.pwmBar.setGeometry(QtCore.QRect(2, 108, 530, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(8)
        self.pwmBar.setFont(font)
        self.pwmBar.setStyleSheet("QProgressBar::chunk {background-color: #06B025;}")
        self.pwmBar.setProperty("value", 0)
        self.pwmBar.setAlignment(QtCore.Qt.AlignCenter)
        self.pwmBar.setFormat("PWM")
        self.pwmBar.setObjectName("pwmBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "数字温度PWM控制仪 - 2017盟升杯"))
        self.temp.setText(_translate("MainWindow", "温度"))
        self.pwm.setText(_translate("MainWindow", "占空比"))
        self.borderL.setText(_translate("MainWindow", "下限"))
        self.borderH.setText(_translate("MainWindow", "上限"))
        self.ip.setText(_translate("MainWindow", "IP:"))
        self.ipDot1.setText(_translate("MainWindow", "."))
        self.ipDot2.setText(_translate("MainWindow", "."))
        self.ipDot3.setText(_translate("MainWindow", "."))
        self.version.setText(_translate("MainWindow", "版本: 未知"))
        self.mac.setText(_translate("MainWindow", "MAC: 未知"))
        self.ipSeg1.setText(_translate("MainWindow", "192"))
        self.ipSeg2.setText(_translate("MainWindow", "168"))
        self.ipSeg3.setText(_translate("MainWindow", "1"))
        self.ipSeg4.setText(_translate("MainWindow", "233"))
        self.connectButton.setText(_translate("MainWindow", "连接"))

