# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(566, 121)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.temp = QtWidgets.QLabel(self.centralwidget)
        self.temp.setGeometry(QtCore.QRect(2, 2, 72, 15))
        self.temp.setObjectName("temp")
        self.pwm = QtWidgets.QLabel(self.centralwidget)
        self.pwm.setGeometry(QtCore.QRect(192, 2, 72, 15))
        self.pwm.setObjectName("pwm")
        self.borderL = QtWidgets.QLabel(self.centralwidget)
        self.borderL.setGeometry(QtCore.QRect(322, 2, 72, 15))
        self.borderL.setObjectName("borderL")
        self.borderH = QtWidgets.QLabel(self.centralwidget)
        self.borderH.setGeometry(QtCore.QRect(452, 2, 72, 15))
        self.borderH.setObjectName("borderH")
        self.ip = QtWidgets.QLabel(self.centralwidget)
        self.ip.setGeometry(QtCore.QRect(2, 100, 72, 15))
        self.ip.setObjectName("ip")
        self.ipDot1 = QtWidgets.QLabel(self.centralwidget)
        self.ipDot1.setGeometry(QtCore.QRect(65, 100, 16, 16))
        self.ipDot1.setObjectName("ipDot1")
        self.ipDot2 = QtWidgets.QLabel(self.centralwidget)
        self.ipDot2.setGeometry(QtCore.QRect(105, 100, 16, 16))
        self.ipDot2.setObjectName("ipDot2")
        self.ipDot3 = QtWidgets.QLabel(self.centralwidget)
        self.ipDot3.setGeometry(QtCore.QRect(145, 100, 16, 16))
        self.ipDot3.setObjectName("ipDot3")
        self.mac = QtWidgets.QLabel(self.centralwidget)
        self.mac.setGeometry(QtCore.QRect(252, 100, 181, 16))
        self.mac.setObjectName("mac")
        self.version = QtWidgets.QLabel(self.centralwidget)
        self.version.setGeometry(QtCore.QRect(452, 100, 121, 16))
        self.version.setObjectName("version")
        self.tempLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.tempLCD.setGeometry(QtCore.QRect(2, 20, 171, 71))
        self.tempLCD.setSmallDecimalPoint(True)
        self.tempLCD.setDigitCount(4)
        self.tempLCD.setProperty("value", 0.0)
        self.tempLCD.setObjectName("tempLCD")
        self.pwmLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.pwmLCD.setGeometry(QtCore.QRect(192, 20, 111, 71))
        self.pwmLCD.setDigitCount(3)
        self.pwmLCD.setProperty("value", 0.0)
        self.pwmLCD.setObjectName("pwmLCD")
        self.borderLLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.borderLLCD.setGeometry(QtCore.QRect(322, 20, 111, 71))
        self.borderLLCD.setDigitCount(3)
        self.borderLLCD.setProperty("value", 0.0)
        self.borderLLCD.setObjectName("borderLLCD")
        self.borderHLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.borderHLCD.setGeometry(QtCore.QRect(452, 20, 111, 71))
        self.borderHLCD.setDigitCount(3)
        self.borderHLCD.setProperty("value", 0.0)
        self.borderHLCD.setObjectName("borderHLCD")
        self.ipSeg1 = QtWidgets.QLineEdit(self.centralwidget)
        self.ipSeg1.setGeometry(QtCore.QRect(32, 98, 31, 21))
        self.ipSeg1.setObjectName("ipSeg1")
        self.ipSeg2 = QtWidgets.QLineEdit(self.centralwidget)
        self.ipSeg2.setGeometry(QtCore.QRect(72, 98, 31, 21))
        self.ipSeg2.setObjectName("ipSeg2")
        self.ipSeg3 = QtWidgets.QLineEdit(self.centralwidget)
        self.ipSeg3.setGeometry(QtCore.QRect(112, 98, 31, 21))
        self.ipSeg3.setObjectName("ipSeg3")
        self.ipSeg4 = QtWidgets.QLineEdit(self.centralwidget)
        self.ipSeg4.setGeometry(QtCore.QRect(152, 98, 31, 21))
        self.ipSeg4.setObjectName("ipSeg4")
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setGeometry(QtCore.QRect(192, 97, 51, 23))
        self.connectButton.setObjectName("connectButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "数字温度PWM控制仪 - 2017盟升杯"))
        self.temp.setText(_translate("MainWindow", "温度:"))
        self.pwm.setText(_translate("MainWindow", "占空比:"))
        self.borderL.setText(_translate("MainWindow", "阈值下限:"))
        self.borderH.setText(_translate("MainWindow", "阈值上限:"))
        self.ip.setText(_translate("MainWindow", "IP: "))
        self.ipDot1.setText(_translate("MainWindow", "."))
        self.ipDot2.setText(_translate("MainWindow", "."))
        self.ipDot3.setText(_translate("MainWindow", "."))
        self.mac.setText(_translate("MainWindow", "MAC: "))
        self.version.setText(_translate("MainWindow", "版本: "))
        self.ipSeg1.setText(_translate("MainWindow", "192"))
        self.ipSeg2.setText(_translate("MainWindow", "168"))
        self.ipSeg3.setText(_translate("MainWindow", "31"))
        self.ipSeg4.setText(_translate("MainWindow", "161"))
        self.connectButton.setText(_translate("MainWindow", "连接"))

